### ISSUE TITLE
this may be of use

### ISSUE THREAD

**Issue by eylles** [kyleraykbs/KyWal#1]
hi, i maintain [pywal16](https://github.com/eylles/pywal16) (sorta, still need to put a release on pypi...) recently i cobbled something that may interest you https://github.com/GradienceTeam/Gradience/issues/780#issuecomment-1703312418

**Comment by kyleraykbs** [comment]
That's rad man! Unfortunately I'm probably going to archive this repo cause Stylix on NixOS has most of this covered.
